### ISSUE TITLE
Question: any interest in collaborating in creating LLMs using GoMLX (an XLA base framework for Go)?

### ISSUE THREAD

**Issue by janpfeifer** [sunhailin-Leo/triton-service-go#31]
hi Leo @sunhailin-Leo ,

This is kind of random, but I thought I would reach out after looking at your repositories with the SentencePiece encoder and the Triton service inference.

I created an ML framework for Go using XLA called [GoMLX](https://github.com/gomlx/gomlx) -- I thought Go should have one, and a slightly different take from TensorFLow/Jax/Pytorch (It's actually more like Jax). 

It's been working nicely for most simpler models (up to diffusion model), and I'm just now starting to work to convert transformer models -- I plan to start with the `google/flan-t5-small` model, for which I needed a Sentencepiece encoder, and  I bumped into your repositories. My current idea is to create a repository under `github.com/gomlx/transfomers`, somewhat inline with Hugging Face one, but for Go.

I was wondering if this is something that would interest you ? 

cheers
Jan

ps.: Everything is OSS. Including a [Jupyter Notebook kernel for Go](https://github.com/janpfeifer/gonb) that I created for this project.

**Comment by sunhailin-Leo** [comment]
@janpfeifer 
* About the model tokenizer, I think using Rust binding(CGO) is the best way to make it compatible with any LLMs. [tokenizers](https://github.com/sunhailin-Leo/tokenizers)
